# Generated by Django 5.1.1 on 2024-09-21 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inflow',
            old_name='updated_true',
            new_name='updated_at',
        ),
    ]
